name: CI for lscma

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install the package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install .[dev]  # Install dev dependencies including sphinx

    - name: Install test dependencies
      run: pip install pytest

    - name: Run tests
      run: pytest

    - name: Build Sphinx Documentation
      run: |
        sphinx-build -b html sphinx docs
